#pragma once
namespace OBJ_ARR {
	enum objarr { STAGE, BOMB, WEAPONE, NOMALBULLET, SKILL, SKILLBULLET, MISSILE, ITEM, ENEMY, ENEMYNORMALBULLET, BOSS, PLAYER, END };

}

enum LEVEL { LV_1, LV_2, LV_3, LV_4, LV_5 };
enum SCENE_ID { NO_EVENT = 11000, MAIN_MENU, STAGE1, STAGE2, STAGE3, STAGE4, GAME_OVER, GAME_EXIT };
enum MOVE {MOVE_LEFT, MOVE_RIGHT, MOVE_UP, MOVE_DOWN, MOVE_END};