#pragma once

enum OBJTYPE { STAGE, PLAYER, OBSTACLE, BULLET, TRAP, ENEMY, END };
enum SCENE_ID { NO_EVENT = 11000, MAIN_MENU, STAGE1, GAME_OVER, GAME_CLEAR, GAME_EXIT };
enum ANIMATION { ANIM_LEFT_IDLE, ANIM_RIGHT_IDLE, ANIM_LEFT, ANIM_RIGHT, ANIM_UP, ANIM_DOWN, ANIM_LEFT_JUMP, ANIM_RIGHT_JUMP, ANIM_END };


namespace ObstacleID
{
	enum OBSTACLE { COMMON, MOVING, RAIL_LEFT, RAIL_RIGHT, WALL, THORN_UP, THORN_DOWN, SHOOTING_UP, SHOOTING_DOWN, SHOOTING_LEFT, SHOOTING_RIGHT, POOP, END };
}

namespace SegmentPos
{
	enum SEGMENT { TOP, BOTTOM, LEFT, RIGHT, END };
}

enum COLLISION { NO_COLLISION, LEFT_COLLISION, RIGHT_COLLISION, TOP_COLLISION, BOTTOM_COLLISION };