#pragma once

enum OBJ_ID { CURSOR, OBJ_MAIN_MENU, SINGLE_PLAY, OBJ_END, STAGE, PLAYER };
enum CURSOR_ID {ARROW, DRAG, HIGHSCROLL, ILLEGAL, LOWSCROLL, MAGG, MAGR, MAGY, TARGG, CURSOR_END };
enum UI_ID { IDLE, MOUSE_OVER, UI_END };
enum SCENE_ID { NO_EVENT = 11000, MAIN_MENU, STAGE1, GAME_OVER, GAME_EXIT };
//enum ANIMATION { ANIM_LEFT_IDLE, ANIM_RIGHT_IDLE, ANIM_LEFT, ANIM_RIGHT, ANIM_UP, ANIM_DOWN, ANIM_LEFT_JUMP, ANIM_RIGHT_JUMP, ANIM_END };

enum ANIMATION_NUM { TYPE_NUM, IMAGE_NUM, ANIMATION_NUM_END };