#pragma once

enum OBJ_ID { CURSOR, OBJ_END, STAGE, PLAYER };
enum BUTTON_ID {SINGLE_PLAY_BUTTON, MULTI_PLAY_BUTTON, EDITOR_BUTTON, EXIT_BUTTON, BUTTON_END};
enum CURSOR_ID {ARROW, CLICK, DRAG, HIGHSCROLL, ILLEGAL, LOWSCROLL, MAGG, MAGR, MAGY, TARGG, CURSOR_END };
enum UI_ID { BUTTON, UI_END };
enum UI_STATE_ID { IDLE, MOUSE_OVER, UI_STATE_END };

namespace SCENE {
	enum SCENE_ID { MAIN_MENU, SINGLE_PLAY, MULTI_PLAY, EDITOR, EXIT, SCENE_END, NO_EVENT
	};
};
//enum ANIMATION { ANIM_LEFT_IDLE, ANIM_RIGHT_IDLE, ANIM_LEFT, ANIM_RIGHT, ANIM_UP, ANIM_DOWN, ANIM_LEFT_JUMP, ANIM_RIGHT_JUMP, ANIM_END };

enum ANIMATION_NUM { TYPE_NUM, IMAGE_NUM, ANIMATION_NUM_END };