#pragma once

enum OBJTYPE { STAGE, PLAYER, END };
enum SCENE_ID { NO_EVENT = 11000, MAIN_MENU, STAGE1, GAME_OVER, GAME_EXIT };
enum ANIMATION { ANIM_LEFT_IDLE, ANIM_RIGHT_IDLE, ANIM_LEFT, ANIM_RIGHT, ANIM_UP, ANIM_DOWN, ANIM_LEFT_JUMP, ANIM_RIGHT_JUMP, ANIM_END };

